apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spam2000
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DanyloVanin/wisey-test-task.git
    targetRevision: main
    path: apps/spam2000
  destination:
    server: https://kubernetes.default.svc
    namespace: spam2000
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
  # PRODUCTION: add ignoreDifferences for fields mutated by controllers (e.g. HPA replicas)
